### ISSUE TITLE
Modifying min_days_remaining forces new resource

### ISSUE THREAD

**Issue by jdextraze** [paybyphone/terraform-provider-acme#13]
Modifying the `min_days_remaining` optional argument should not forces new resource.

Terraform version: 0.9.4
Terraform acme provider version: 0.3.0

**Comment by vancluever** [comment]
Hey @jdextraze!

Yeah - kinda wondering why I did that now but I can't think of any good reason - think this can just be updated in the schema and it be good to go. Will do that ASAP and push out a new release!

**Comment by jdextraze** [comment]
Thanks @vancluever for the quick answer. I found a way to get around it by modifying the state, so no rush.

**Comment by vancluever** [comment]
Good to know! I'm reviewing what would need to happen to get this 100% working. I had to refresh my memory on why exactly it was `ForceNew` in the first place, the reason being that there is no update function in this resource due to how renewal of the certificate works (auto-renewal is a process that requires no configuration modification, so there is essentially nothing to update without a complete re-generation of the certificate).

I just need to dissect the workflow a bit to see what needs to happen so that updates to `min_days_remaining` go through immediately. There used to be an issue with Terraform (pre-data sources) where read-only resources (which this resource very much behaves like) sometimes took multiple updates for config modifications to properly propagate updates to dependent resources and I want to make sure this doesn't happen here.

**Comment by vancluever** [comment]
Hey @jdextraze, just to mention some progress on this - I am working on a feature that will offer a solution to this and #15 - basically the ability for the provider to be able to control the diff outside of config. You can track the progress of the PR here: hashicorp/terraform#14887

What this will allow me to do is control how the certificate is diffed so that the certificate logically switches back to a computed state in the diff when it's at its renewal point, allowing the update to properly renew it. This ultimately will give a real use case for having an `Update` function in this resource, which will allow for attributes that are not `ForceNew`.

I'm guessing having it into master and fully released will probably be a few weeks, but after that's done I will be working on updating the plugin to use the new logic. Will update more then!

**Comment by vancluever** [comment]
Hey @jdextraze, version v0.4.0 is now out which fixes this issue - as such closing this now, but let me know if there's any issues (especially since the update to v0.10.0-beta2 as the base).

Cheers!
